# -*- coding: utf-8 -*-
"""ev_charging.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E2onMKtdlC7t9B6uR2qKHHFojHx75HV0
"""

import pandas as pd
import numpy as np

df = pd.read_csv("ev_charging_dataset.csv")

df.head()

df.info()

df.shape

df.columns = df.columns.str.strip()
df.columns = df.columns.str.replace(" ", "_")
df.columns = df.columns.str.replace("%", "")
df.columns = df.columns.str.replace("/", "_")
df.columns = df.columns.str.replace("(", "")
df.columns = df.columns.str.replace(")", "")

print(df.columns)

df['Date_Time'] = pd.to_datetime(df['Date_Time'])

df['Hour'] = df['Date_Time'].dt.hour
df['Day'] = df['Date_Time'].dt.day
df['Month'] = df['Date_Time'].dt.month

df.head()

df.dtypes

df['Vehicle_ID'] = df['Vehicle_ID'].astype(int)

duplicate_count = df.duplicated().sum()
print("Number of duplicate rows:", duplicate_count)
df = df.drop_duplicates()
print("After removing duplicates:", df.duplicated().sum())

df.isnull().sum()

df.describe()

print("\nRoad Conditions:", df['Road_Conditions'].unique())
print("Weather Conditions:", df['Weather_Conditions'].unique())

df['Charging_Load_kW'].hist(bins=50)
plt.title("Charging Load Distribution")
plt.xlabel("Charging Load (kW)")
plt.ylabel("Frequency")
plt.show()

df['State_of_Charge_'].hist(bins=50)
plt.title("State of Charge Distribution")
plt.show()

plt.scatter(df['Hour'], df['Charging_Load_kW'], alpha=0.3)
plt.title("Charging Load vs Hour")
plt.xlabel("Hour")
plt.ylabel("Charging Load")
plt.show()

plt.scatter(df['Distance_to_Destination_km'], df['Energy_Consumption_Rate_kWh_km'], alpha=0.3)
plt.title("Distance vs Energy Consumption")
plt.show()

plt.scatter(df['Queue_Time_mins'], df['Charging_Load_kW'], alpha=0.3)
plt.title("Queue Time vs Charging Load")
plt.show()

df['Battery_Energy_kWh'] = (df['State_of_Charge_'] / 100) * df['Battery_Capacity_kWh']

df['Energy_Required_kWh'] = df['Distance_to_Destination_km'] * df['Energy_Consumption_Rate_kWh_km']

df['Energy_Deficit'] = df['Energy_Required_kWh'] - df['Battery_Energy_kWh']

df = pd.get_dummies(df, columns=['Road_Conditions', 'Weather_Conditions'], drop_first=True)

df = df.drop(columns=['Vehicle_ID', 'Charging_Station_ID', 'Date_Time'])

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

num_cols = df.select_dtypes(include=['float64', 'int64']).columns
df[num_cols] = scaler.fit_transform(df[num_cols])

from sklearn.model_selection import train_test_split

train_df, test_df = train_test_split(df, test_size=0.1, random_state=42)

state_features = [
    'State_of_Charge_',
    'Distance_to_Destination_km',
    'Traffic_Data',
    'Queue_Time_mins',
    'Battery_Energy_kWh',
    'Energy_Deficit',
    'Hour'
]

X_train = train_df[state_features]
X_test = test_df[state_features]

y_train = train_df['Charging_Load_kW']
y_test = test_df['Charging_Load_kW']

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

model = RandomForestRegressor(n_estimators=50, random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
print("MSE:", mse)

train_df.to_csv("train_ev_data.csv", index=False)
test_df.to_csv("test_ev_data.csv", index=False)

import pandas as pd
import numpy as np

train_df = pd.read_csv("train_ev_data.csv")

class EVEnvironment:
    def __init__(self, data):
        self.data = data.reset_index(drop=True)
        self.current_step = 0
        self.max_steps = len(data)

    def reset(self):
        self.current_step = 0
        return self._get_state()

    def _get_state(self):
        row = self.data.iloc[self.current_step]
        return (
            round(row['State_of_Charge_'], 2),
            round(row['Distance_to_Destination_km'], 2),
            round(row['Traffic_Data'], 2),
            round(row['Queue_Time_mins'], 2),
            round(row['Energy_Deficit'], 2)
        )

    def step(self, action):
        row = self.data.iloc[self.current_step]

        reward = 0

        if action == 0:
            reward -= row['Distance_to_Destination_km'] * 0.5
            if row['Energy_Deficit'] > 0:
                reward -= 20

        elif action == 1:
            reward -= row['Queue_Time_mins'] * 0.2
            reward += 10

        elif action == 2:
            reward -= 5

        self.current_step += 1
        done = self.current_step >= self.max_steps

        next_state = self._get_state() if not done else None

        return next_state, reward, done

import random

class QLearningAgent:
    def __init__(self, actions):
        self.q_table = {}
        self.actions = actions
        self.alpha = 0.1
        self.gamma = 0.9
        self.epsilon = 0.2

    def get_q(self, state, action):
        return self.q_table.get((state, action), 0)

    def choose_action(self, state):
        if random.uniform(0, 1) < self.epsilon:
            return random.choice(self.actions)
        else:
            q_values = [self.get_q(state, a) for a in self.actions]
            return self.actions[np.argmax(q_values)]

    def learn(self, state, action, reward, next_state):
        current_q = self.get_q(state, action)

        if next_state is None:
            max_future_q = 0
        else:
            max_future_q = max([self.get_q(next_state, a) for a in self.actions])

        new_q = current_q + self.alpha * (reward + self.gamma * max_future_q - current_q)
        self.q_table[(state, action)] = new_q

env = EVEnvironment(train_df)
agent = QLearningAgent(actions=[0, 1, 2])

episodes = 50

for episode in range(episodes):
    state = env.reset()
    total_reward = 0

    while True:
        action = agent.choose_action(state)
        next_state, reward, done = env.step(action)

        agent.learn(state, action, reward, next_state)

        state = next_state
        total_reward += reward

        if done:
            break

    print(f"Episode {episode+1}: Total Reward = {total_reward}")

state = env.reset()
total_reward = 0

while True:
    action = agent.choose_action(state)
    next_state, reward, done = env.step(action)

    total_reward += reward
    state = next_state

    if done:
        break

print("Test Total Reward:", total_reward)

# If not installed
# pip install torch

import torch
import torch.nn as nn
import torch.optim as optim
import random
import numpy as np
import pandas as pd
from collections import deque

train_df = pd.read_csv("train_ev_data.csv")

class EVEnvironment:
    def __init__(self, data):
        self.data = data.reset_index(drop=True)
        self.max_steps = len(data)
        self.current_step = 0

    def reset(self):
        self.current_step = 0
        return self._get_state()

    def _get_state(self):
        row = self.data.iloc[self.current_step]
        return np.array([
            row['State_of_Charge_'],
            row['Distance_to_Destination_km'],
            row['Traffic_Data'],
            row['Queue_Time_mins'],
            row['Energy_Deficit'],
            row['Hour']
        ], dtype=np.float32)

    def step(self, action):
        row = self.data.iloc[self.current_step]

        reward = 0

        if action == 0:
            reward -= row['Distance_to_Destination_km']
            if row['Energy_Deficit'] > 0:
                reward -= 20

        elif action == 1:
            reward -= row['Queue_Time_mins']
            reward += 15

        elif action == 2:
            reward -= 5

        self.current_step += 1
        done = self.current_step >= self.max_steps

        next_state = self._get_state() if not done else np.zeros(6)

        return next_state, reward, done

class DQN(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(DQN, self).__init__()
        self.fc = nn.Sequential(
            nn.Linear(input_dim, 64),
            nn.ReLU(),
            nn.Linear(64, 64),
            nn.ReLU(),
            nn.Linear(64, output_dim)
        )

    def forward(self, x):
        return self.fc(x)

class ReplayBuffer:
    def __init__(self, capacity=10000):
        self.buffer = deque(maxlen=capacity)

    def push(self, state, action, reward, next_state, done):
        self.buffer.append((state, action, reward, next_state, done))

    def sample(self, batch_size):
        batch = random.sample(self.buffer, batch_size)
        return zip(*batch)

    def __len__(self):
        return len(self.buffer)

env = EVEnvironment(train_df)

state_dim = 6
action_dim = 3

model = DQN(state_dim, action_dim)
target_model = DQN(state_dim, action_dim)

target_model.load_state_dict(model.state_dict())

optimizer = optim.Adam(model.parameters(), lr=0.001)
loss_fn = nn.MSELoss()

buffer = ReplayBuffer()

episodes = 50
batch_size = 32
gamma = 0.9
epsilon = 1.0
epsilon_decay = 0.995
epsilon_min = 0.05

for episode in range(episodes):
    state = env.reset()
    total_reward = 0

    while True:
        state_tensor = torch.FloatTensor(state)

        if random.random() < epsilon:
            action = random.randint(0, action_dim - 1)
        else:
            with torch.no_grad():
                q_values = model(state_tensor)
                action = torch.argmax(q_values).item()

        next_state, reward, done = env.step(action)

        buffer.push(state, action, reward, next_state, done)

        state = next_state
        total_reward += reward

        if len(buffer) > batch_size:
            states, actions, rewards, next_states, dones = buffer.sample(batch_size)

            states = torch.FloatTensor(list(states))
            actions = torch.LongTensor(list(actions))
            rewards = torch.FloatTensor(list(rewards))
            next_states = torch.FloatTensor(list(next_states))
            dones = torch.FloatTensor(list(dones))

            q_values = model(states)
            next_q_values = target_model(next_states)

            q_value = q_values.gather(1, actions.unsqueeze(1)).squeeze()
            max_next_q = next_q_values.max(1)[0]

            target = rewards + gamma * max_next_q * (1 - dones)

            loss = loss_fn(q_value, target.detach())

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

        if done:
            break

    target_model.load_state_dict(model.state_dict())

    epsilon = max(epsilon * epsilon_decay, epsilon_min)

    print(f"Episode {episode+1}, Reward: {total_reward}, Epsilon: {epsilon:.3f}")

state = env.reset()
total_reward = 0

while True:
    state_tensor = torch.FloatTensor(state)

    with torch.no_grad():
        action = torch.argmax(model(state_tensor)).item()

    next_state, reward, done = env.step(action)

    total_reward += reward
    state = next_state

    if done:
        break

print("Test Total Reward:", total_reward)

torch.save(model.state_dict(), "dqn_ev_model.pth")

episode_rewards = []

episode_rewards.append(total_reward)

for episode in range(episodes):
    state = env.reset()
    total_reward = 0

    while True:

        if done:
            break

    episode_rewards.append(total_reward)
    print(f"Episode {episode+1}, Reward: {total_reward}, Epsilon: {epsilon:.3f}")

import matplotlib.pyplot as plt

plt.plot(episode_rewards)
plt.title("DQN Training Rewards")
plt.xlabel("Episode")
plt.ylabel("Total Reward")
plt.show()

np.save("dqn_rewards.npy", episode_rewards)

